### ISSUE TITLE
Doesn't always work right

### ISSUE THREAD

**Issue by gundogduyakici** [catalinmiron/react-native-wheel-of-fortune#2]
Thank you for your hard work! Unfortunately the winner index will be determined wrong sometimes. Especially when you rotate the wheel from right bottom to right up. The other way around works pretty good.

Also in your expo is the problem, so it seems that there is a pretty annoying bug in your code.

Do you have a solution for that? The winner index should be 100% right because if not, the game doesn't make any sense when you're winning the wrong values :D

Thanks in advance!﻿

**Comment by uzegonemad** [comment]
I'm not sure if my math is 100% correct but replacing my `_getWinnerIndex()` function with the following seemed to solve the issue for me.

```js
_getWinnerIndex = () => {
    const deg = Math.abs(Math.round(this.angle % oneTurn));

    // wheel turning counterclockwise
    if(this.angle < 0)
    {
        return Math.floor(deg / angleBySegment);
    }

    // wheel turning clockwise
    return (numberOfSegments - Math.floor(deg / angleBySegment)) % numberOfSegments;
};
```

**Comment by luco** [comment]
@uzegonemad Thanks, works perfectly!

**Comment by gundogduyakici** [comment]
@uzegonemad Big thanks! Worked.
